import { SCSInput } from './interfaces';

export const sampleInputs: {[index: string]: SCSInput } = {
  "4キラーマ等速": {
    friends: [
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 6,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 6,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 6,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 6,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "ホイミスライム",
        lv: 30,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "スモールグール",
        lv: 30,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "ホイミスライム",
        lv: 30,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
    ],
    field: {
      row: 10,
      col: 10,
      data: [
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  0,  0,  1,  1,  1,
        1,  1,  0, 19,  0,  0,  0,  1,  1,  1,
        1,  1, 10, 11, 12, 13, 14,  1,  1,  1,
        1,  1,  9,  9,  9,  9,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  0,  1,  1,  1,  1,
        1,  1, 15, 16, 17, 18,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  0,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  0,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
      ]
    },
    config: {
      turn: 1500,
      trial: 100,
    }
  },
  "4キラーマ倍速": {
    friends: [
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: true,
        hpDope: 1,
        weakenAtk: 6,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: true,
        hpDope: 0,
        weakenAtk: 6,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: true,
        hpDope: 0,
        weakenAtk: 6,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: true,
        hpDope: 0,
        weakenAtk: 6,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "ホイミスライム",
        lv: 30,
        doubleSpeed: true,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: true,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: true,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: true,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "スモールグール",
        lv: 30,
        doubleSpeed: true,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "ホイミスライム",
        lv: 30,
        doubleSpeed: true,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
    ],
    field: {
      row: 10,
      col: 10,
      data: [
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  0,  0,  1,  1,  1,
        1,  1,  0, 19,  0,  0,  0,  1,  1,  1,
        1,  1, 10, 11, 12, 13, 14,  1,  1,  1,
        1,  1,  9,  9,  9,  9,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  0,  1,  1,  1,  1,
        1,  1, 15, 16, 17, 18,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  0,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  0,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
      ]
    },
    config: {
      turn: 1500,
      trial: 100,
    }
  },
  "3キラーマ等速": {
    friends: [
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 6,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 6,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 6,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "ホイミスライム",
        lv: 30,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "スモールグール",
        lv: 30,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "ホイミスライム",
        lv: 30,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
    ],
    field: {
      row: 10,
      col: 10,
      data: [
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  0,  1,  1,  1,  1,
        1,  1,  0, 19,  0,  0,  1,  1,  1,  1,
        1,  1, 10, 11, 12, 14,  1,  1,  1,  1,
        1,  1,  0,  0,  9,  1,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  1,  1,  1,  1,  1,
        1,  1, 15, 16, 17,  1,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  1,  1,  1,  1,  1,
        1,  1, 13, 18,  0,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
      ]
    },
    config: {
      turn: 1500,
      trial: 100,
    }
  },
  "キノコtest": {
    friends: [
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 6,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 6,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 6,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "ホイミスライム",
        lv: 30,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "おばけキノコ",
        lv: 20,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "スモールグール",
        lv: 30,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
      {
        name: "ホイミスライム",
        lv: 30,
        doubleSpeed: false,
        hpDope: 0,
        weakenAtk: 0,
        weakenDef: 0,
        isSealed: false,
      },
    ],
    field: {
      row: 10,
      col: 10,
      data: [
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  0,  1,  1,  1,  1,
        1,  1,  0, 19,  0,  0,  1,  1,  1,  1,
        1,  1, 10, 11, 12, 14,  1,  1,  1,  1,
        1,  1,  0,  0,  9,  1,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  1,  1,  1,  1,  1,
        1,  1, 15, 16, 17,  1,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  1,  1,  1,  1,  1,
        1,  1, 13, 18,  0,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
      ]
    },
    config: {
      turn: 1500,
      trial: 100,
    }
  },
};
